### ISSUE TITLE
Refactor all functioning classes to match CA specifications

### ISSUE THREAD

**Issue by musicofmusix** [52259tan/UofTCourseScheduleOptimizer#18]
A lot of things to do... I need everyone on the team to help out with this.
Right now our functionality is mostly done - let's try to convert the entire project to conform to the CA architecture during the weekend/start of next week.

## Checklist
- [ ] Confirm use case functionality works from start to finish. Merge everything to main. Highlight the final "working" commit on main.
- [ ] Create a main-CA branch to exclusively work on CA conversion.
- [ ] Any new functionality updates/bugfixes done on other branches to be merged into main and then also into the main-CA branch, as soon as possible.
- [ ] Since the whole structure may be daunting, I have made a diagram as a first start:
![CSC207_CA](https://github.com/52259tan/UofTCourseScheduleOptimizer/assets/18087232/a56c4dee-e58b-46cc-90c2-00c791991a19)
- [ ] Here is a mockup of the UI/View that I am _suggesting_:
![CSC207_CA_UI](https://github.com/52259tan/UofTCourseScheduleOptimizer/assets/18087232/97281b9b-ee9e-4127-bfe0-e2b86559d869)

**Some notes on the implementation**
- Due to my ignorance, I may not have included some "intermediate helper classes" that everyone is using (e.g. "Manager Classes"), but I have placed DistanceManager and MapRenderManager as examples.
- Most of our work would be to put all of our functionality into the single large use case interactor, and making the 2~3 input/output boundaries.

There are bound to be some important decisions to make, let's try to get them on GitHub issues ASAP when encountering them.

**Comment by pingluuu** [comment]
Thank you, Joshua, the graph is clear and I appreciate your dedication so much! I will review this later today or early tomorrow and get back to you what I think.
