### ISSUE TITLE
Algorithm and getDistance mismatch

### ISSUE THREAD

**Issue by 52259tan** [52259tan/UofTCourseScheduleOptimizer#21]
Hi just want to bring attention to Ping and Josh that there is a small mismatch with `DistanceManager.getDistance( **PARAMETER MISTMATCH**`)

- In algorithm/getDistances.java method calls

![image](https://github.com/52259tan/UofTCourseScheduleOptimizer/assets/123585469/65a1f661-48c3-4521-a487-79f8c6f38c72)

- in the Distance/DistanceManager.

![image](https://github.com/52259tan/UofTCourseScheduleOptimizer/assets/123585469/73e0faa9-bfdf-4739-b8e6-191a2ee3663f)

**Comment by musicofmusix** [comment]
getDistance() in getDistances is a placeholder for an upcoming change to DistanceManager, as per #7. Will close this issue alongside it.
