### ISSUE TITLE
Can't run Demo: getDistance not implemented

### ISSUE THREAD

**Issue by percy-ai** [52259tan/UofTCourseScheduleOptimizer#24]
Hi everyone, after updating **_percy-view_** with new changes from **_main_**, the demo files suddenly could not be run :( If possible can anyone make a mock **_getDistance_** method (don't even need to be accurate since the demo don't use it) so that the program would compile? 

<img width="1242" alt="Screen Shot 2023-11-26 at 4 20 41 PM" src="https://github.com/52259tan/UofTCourseScheduleOptimizer/assets/144645042/e3d0ad3f-55ad-4080-8314-bb11f6c56fb6">

**Comment by musicofmusix** [comment]
The latest commit/merge to main should resolve this now that getDistance is properly implemented - or you can comment that line out during testing.

**Comment by percy-ai** [comment]
fyp I recently discovered that you can Exclude file/directory on IntelliJ to avoid compiler error :) my bad hehe
