### ISSUE TITLE
Need method in DistanceManager which returns the distance between two buildings

### ISSUE THREAD

**Issue by musicofmusix** [52259tan/UofTCourseScheduleOptimizer#7]
Currently, DistanceManager only has a method to return all possible building-building distance combinations in a giant list, given a list of courses. Requested by @pingluuu for the Optimisation Algorithm.

The new getDistance() method should:
- parameters: origin building code (String), destination building code (String). Order does not matter.
- return: distance between the two buildings, in meters (Double)

**Comment by pingluuu** [comment]
Thank you Joshua, you got this!
